APRENDENDO A UTILIZAR A BIBLIOTECA PANDAS
    
    A biblioteca Pandas é uma ferramenta poderosa para manipulação e análise de dados em Python. Ela oferece estruturas de dados de alto nível, como DataFrames e Series, que facilitam o trabalho com dados tabulares, como aqueles encontrados em planilhas e bancos de dados.

    A biblioteca Pandas é essencial para qualquer trabalho de análise de dados em Python, oferecendo uma ampla gama de funcionalidades para facilitar a manipulação e análise de grandes conjuntos de dados.

    --> o que são arquivos CSV? Arquivos CSV (Comma-Separated Values) são arquivos de texto simples que armazenam dados tabulares, como planilhas e tabelas, onde cada linha representa uma linha de dados e cada campo é separado por uma vírgula

pandas fornece funções para leitura de vários tipos de arquivos, sendo eles:
1. csv
2. excel
3. JSON

In [1]:
# geralmente é usado pandas juntamente com numpy

import pandas as pd
import numpy as np

O QUE É IRIS DATASET?

são dados variados de uma flor iris, servirão aqui como exemplo para aplicação de estudo

In [3]:
#importação de arquivo

# usar o header = None para informar que não há cabeçalho, caso contrário ele considerará a primeira linha de dados como cabeçalho
iris = pd.read_csv('iris.data', header=None)
iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#agora adicionaremos nomes as colunas usando col_names
col_names = ['sepal_length','sepal_widith', 'petal_length','petal_width','species']
iris = pd.read_csv('iris.data', names = col_names)

iris

     sepal_length  sepal_widith  petal_length  petal_width         species
0             5.1           3.5           1.4          0.2     Iris-setosa
1             4.9           3.0           1.4          0.2     Iris-setosa
2             4.7           3.2           1.3          0.2     Iris-setosa
3             4.6           3.1           1.5          0.2     Iris-setosa
4             5.0           3.6           1.4          0.2     Iris-setosa
..            ...           ...           ...          ...             ...
145           6.7           3.0           5.2          2.3  Iris-virginica
146           6.3           2.5           5.0          1.9  Iris-virginica
147           6.5           3.0           5.2          2.0  Iris-virginica
148           6.2           3.4           5.4          2.3  Iris-virginica
149           5.9           3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

DATAFRAME

É uma estrutura de dados, que armazena dados em forma de tabela, com linhas e colunas. é mostrado aqui no ambiente de desenvolvimento.

In [5]:
# utilizando da maneira abaixo, que é uma forma padrão de visualização do jupyter, podemos ver a estrutura toda editada e bonita
iris

     sepal_length  sepal_widith  petal_length  petal_width         species
0             5.1           3.5           1.4          0.2     Iris-setosa
1             4.9           3.0           1.4          0.2     Iris-setosa
2             4.7           3.2           1.3          0.2     Iris-setosa
3             4.6           3.1           1.5          0.2     Iris-setosa
4             5.0           3.6           1.4          0.2     Iris-setosa
..            ...           ...           ...          ...             ...
145           6.7           3.0           5.2          2.3  Iris-virginica
146           6.3           2.5           5.0          1.9  Iris-virginica
147           6.5           3.0           5.2          2.0  Iris-virginica
148           6.2           3.4           5.4          2.3  Iris-virginica
149           5.9           3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
# podemos printar o dataframe de forma direta usando o print

print(iris)

     sepal_length  sepal_widith  petal_length  petal_width         species
0             5.1           3.5           1.4          0.2     Iris-setosa
1             4.9           3.0           1.4          0.2     Iris-setosa
2             4.7           3.2           1.3          0.2     Iris-setosa
3             4.6           3.1           1.5          0.2     Iris-setosa
4             5.0           3.6           1.4          0.2     Iris-setosa
..            ...           ...           ...          ...             ...
145           6.7           3.0           5.2          2.3  Iris-virginica
146           6.3           2.5           5.0          1.9  Iris-virginica
147           6.5           3.0           5.2          2.0  Iris-virginica
148           6.2           3.4           5.4          2.3  Iris-virginica
149           5.9           3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

VISUALIZAR E INSPECIONAR DADOS

Pandas oferece várias formas de visualizar os dados em um dataframe

In [8]:
# printa as 5 primeiras informações do dataframe
print(iris.head())

# printa o numero de informações passadas como parâmetro
print(iris.head(10))

   sepal_length  sepal_widith  petal_length  petal_width      species
0           5.1           3.5           1.4          0.2  Iris-setosa
1           4.9           3.0           1.4          0.2  Iris-setosa
2           4.7           3.2           1.3          0.2  Iris-setosa
3           4.6           3.1           1.5          0.2  Iris-setosa
4           5.0           3.6           1.4          0.2  Iris-setosa
   sepal_length  sepal_widith  petal_length  petal_width      species
0           5.1           3.5           1.4          0.2  Iris-setosa
1           4.9           3.0           1.4          0.2  Iris-setosa
2           4.7           3.2           1.3          0.2  Iris-setosa
3           4.6           3.1           1.5          0.2  Iris-setosa
4           5.0           3.6           1.4          0.2  Iris-setosa
5           5.4           3.9           1.7          0.4  Iris-setosa
6           4.6           3.4           1.4          0.3  Iris-setosa
7           5.0           3.4           1.5          0.2  Iris-setosa
8           4.4           2.9           1.4          0.2  Iris-setosa
9           4.9           3.1           1.5          0.1  Iris-setosa

In [9]:
#mostra as ultimas informações da base de dados
print(iris.tail())

     sepal_length  sepal_widith  petal_length  petal_width         species
145           6.7           3.0           5.2          2.3  Iris-virginica
146           6.3           2.5           5.0          1.9  Iris-virginica
147           6.5           3.0           5.2          2.0  Iris-virginica
148           6.2           3.4           5.4          2.3  Iris-virginica
149           5.9           3.0           5.1          1.8  Iris-virginica

In [10]:
# solicitando informações importantes do dataframe
print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_widith  150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

In [11]:
# a função describe() traz informações importantes sobre a base de dados, informações estatísticas realmente.

print(iris.describe())

       sepal_length  sepal_widith  petal_length  petal_width
count    150.000000    150.000000    150.000000   150.000000
mean       5.843333      3.054000      3.758667     1.198667
std        0.828066      0.433594      1.764420     0.763161
min        4.300000      2.000000      1.000000     0.100000
25%        5.100000      2.800000      1.600000     0.300000
50%        5.800000      3.000000      4.350000     1.300000
75%        6.400000      3.300000      5.100000     1.800000
max        7.900000      4.400000      6.900000     2.500000

In [14]:
# verificando o tamanho do banco de dados caso não saibamos
# retorna linhas, colunas
print(iris.shape)

(150, 5)

FUNÇÕES ESTATÍSTICAS DO PANDAS

A biblioteca Pandas oferece várias funções estatísticas úteis para análise de dados. Aqui estão algumas das principais:

1. **mean()**: Calcula a média dos valores.
   ```python
   df['coluna'].mean()
   ```

2. **median()**: Determina a mediana dos valores.
   ```python
   df['coluna'].median()
   ```

3. **std()**: Calcula o desvio padrão.
   ```python
   df['coluna'].std()
   ```

4. **var()**: Calcula a variância.
   ```python
   df['coluna'].var()
   ```

5. **min() e max()**: Encontram o valor mínimo e máximo, respectivamente.
   ```python
   df['coluna'].min()
   df['coluna'].max()
   ```

6. **describe()**: Fornece um resumo estatístico, incluindo contagem, média, desvio padrão, valores mínimos e máximos, e percentis.
   ```python
   df.describe()
   ```

7. **corr()**: Calcula a correlação entre colunas.
   ```python
   df.corr()
   ```

8. **count()**: Conta o número de valores não nulos.
   ```python
   df['coluna'].count()
   ```

Essas funções permitem uma análise detalhada e eficiente dos dados numéricos³⁴. Se precisar de mais detalhes ou exemplos específicos, sinta-se à vontade para perguntar!

Fonte: conversa com o Copilot, 06/08/2024
(1) Biblioteca Pandas no Python: o que é e como utilizar. https://bing.com/search?q=fun%c3%a7%c3%b5es+estat%c3%adsticas+da+biblioteca+pandas.
(2) Biblioteca Pandas no Python: o que é e como utilizar. https://www.escoladnc.com.br/blog/introducao-a-biblioteca-pandas-no-python-guia-completo-para-analise-de-dados-tabulares/.
(3) 10 funções mais usadas para manipular dataframes no Pandas. https://insightlab.ufc.br/10-funcoes-mais-usadas-para-manipular-dataframes-no-pandas/.
(4) 28 comandos úteis de Pandas que talvez você não conheça. https://paulovasconcellos.com.br/28-comandos-%C3%BAteis-de-pandas-que-talvez-voc%C3%AA-n%C3%A3o-conhe%C3%A7a-6ab64beefa93.

In [18]:
print(iris.count())
print(iris.sum())

sepal_length    150
sepal_widith    150
petal_length    150
petal_width     150
species         150
dtype: int64
sepal_length                                                876.5
sepal_widith                                                458.1
petal_length                                                563.8
petal_width                                                 179.8
species         Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [23]:
# acessando colunas individualmente

print(iris[['petal_length', 'sepal_widith']])

     petal_length  sepal_widith
0             1.4           3.5
1             1.4           3.0
2             1.3           3.2
3             1.5           3.1
4             1.4           3.6
..            ...           ...
145           5.2           3.0
146           5.0           2.5
147           5.2           3.0
148           5.4           3.4
149           5.1           3.0

[150 rows x 2 columns]

In [26]:
# acessando linhas individualmente
iris.loc[0]

# acessando conjunto de linhas
iris.loc[0:10]

    sepal_length  sepal_widith  petal_length  petal_width      species
0            5.1           3.5           1.4          0.2  Iris-setosa
1            4.9           3.0           1.4          0.2  Iris-setosa
2            4.7           3.2           1.3          0.2  Iris-setosa
3            4.6           3.1           1.5          0.2  Iris-setosa
4            5.0           3.6           1.4          0.2  Iris-setosa
5            5.4           3.9           1.7          0.4  Iris-setosa
6            4.6           3.4           1.4          0.3  Iris-setosa
7            5.0           3.4           1.5          0.2  Iris-setosa
8            4.4           2.9           1.4          0.2  Iris-setosa
9            4.9           3.1           1.5          0.1  Iris-setosa
10           5.4           3.7           1.5          0.2  Iris-setosa

In [28]:
# acessando as informações de cada linha, especificando a linha, exemplo, 10 informações da coluna 3
iris.iloc[0:10, 2]

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
5    1.7
6    1.4
7    1.5
8    1.4
9    1.5
Name: petal_length, dtype: float64